name: Build & Push to External Registry

on:
  workflow_call:
    inputs:
      docker_file_path:
        description: "The path to the Dockerfile"
        required: false
        type: string
        default: ./Dockerfile
      docker_context_path:
        description: "The path to the docker context"
        required: false
        type: string
        default: .
      docker_target:
        description: "The target to build"
        required: false
        type: string
      docker_labels:
        description: "List of metadata for the image"
        required: false
        type: string
      external_registry:
        description: "External registry to push image to"
        required: true
        type: string
    secrets:
      registry_username:
        description: "Username to login to registry"
        required: false
      registry_pw:
        description: "Password to login to registry"
        required: false

jobs:

  build-and-publish:
    name: 'Build & Publish'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Login to External Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.external_registry }}
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_pw }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push to External Registry
        uses: docker/build-push-action@v2
        with:
          # All layers should be cached to optimize for multi-environment deploys
          # Can't cache locally. Blocked by https://github.com/docker/build-push-action/issues/252
          #cache-from: type=local,src=/tmp/.buildx-cache
          #cache-to: type=local,dest=/tmp/.buildx-cache
          cache-from: type=gha,src=/tmp/.buildx-cache
          cache-to: type=gha,dest=/tmp/.buildx-cache-new
          context: "${{ inputs.docker_context_path }}"
          file: "${{ inputs.docker_file_path }}"
          labels: ${{ inputs.docker_labels }}
          platforms: linux/amd64
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ inputs.docker_target }}
          target: ${{ inputs.docker_target }}
          build-args: ${{ secrets.BUILD_ARGS }}
